@extends('layouts.admin')

@section('title', 'Reports Management')

@section('content')
<div class="container mx-auto py-6">
    <!-- Page Header with Back Button -->
    <div class="mb-6 flex items-center justify-between flex-wrap gap-3">
        <div class="flex items-center space-x-3">
            <a href="{{ route('admin.dashboard') }}"
               class="inline-flex items-center bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-200 px-3 py-2 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition">
                <i data-feather="arrow-left" class="w-4 h-4 mr-1"></i> Back
            </a>
            <h2 class="text-2xl font-bold text-indigo-700 flex items-center">
                <i data-feather="bar-chart-2" class="w-6 h-6 mr-2"></i> Reports Overview
            </h2>
        </div>
    </div>

    <p class="text-gray-600 dark:text-gray-400 mb-4">
        View, filter, and manage all system-generated reports.
    </p>

    <!-- Search Bar -->
    <form method="GET" action="{{ route('admin.reports.index') }}" class="mb-6 flex flex-wrap gap-2 items-center">
        <input 
            type="text" 
            name="search" 
            value="{{ request('search') }}" 
            placeholder="Search by title, category, or date..."
            class="w-full md:w-1/3 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:outline-none"
        >
        <button type="submit" 
                class="flex items-center bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
            <i data-feather="search" class="w-4 h-4 mr-1"></i> Search
        </button>
    </form>

    <!-- Reports Table -->
    @if($reports->count() > 0)
        <div class="overflow-x-auto bg-white shadow-lg rounded-lg">
            <table class="min-w-full border border-gray-200 text-sm text-left">
                <thead class="bg-indigo-600 text-white">
                    <tr>
                        <th class="py-3 px-4">#</th>
                        <th class="py-3 px-4">Report Title</th>
                        <th class="py-3 px-4">Category</th>
                        <th class="py-3 px-4">Generated By</th>
                        <th class="py-3 px-4">Date Created</th>
                        <th class="py-3 px-4">Status</th>
                        <th class="py-3 px-4 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reports as $index => $report)
                        <tr class="border-b hover:bg-gray-50 transition">
                            <td class="py-3 px-4">{{ $loop->iteration + ($reports->currentPage() - 1) * $reports->perPage() }}</td>
                            <td class="py-3 px-4 font-semibold text-gray-800">{{ $report->title }}</td>
                            <td class="py-3 px-4">{{ $report->category ?? '—' }}</td>
                            <td class="py-3 px-4">{{ $report->generated_by ?? 'System' }}</td>
                            <td class="py-3 px-4">{{ $report->created_at->format('d M Y, H:i') }}</td>
                            <td class="py-3 px-4">
                                <span class="px-2 py-1 rounded text-xs font-semibold
                                    {{ $report->status == 'Completed' ? 'bg-green-100 text-green-700' : 
                                       ($report->status == 'Pending' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700') }}">
                                    {{ ucfirst($report->status) }}
                                </span>
                            </td>
                            <td class="py-3 px-4 text-center flex justify-center space-x-3">
                                <!-- View -->
                                <a href="{{ route('admin.reports.show', $report->id) }}" 
                                   class="text-blue-600 hover:text-blue-800" title="View Report">
                                    <i data-feather="eye"></i>
                                </a>

                                <!-- Download -->
                                <a href="{{ route('admin.reports.download', $report->id) }}" 
                                   class="text-green-600 hover:text-green-800" title="Download PDF">
                                    <i data-feather="download"></i>
                                </a>

                                <!-- Delete -->
                                <form action="{{ route('admin.reports.destroy', $report->id) }}" method="POST" 
                                      onsubmit="return confirm('Are you sure you want to delete this report?')">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="text-red-600 hover:text-red-800" title="Delete">
                                        <i data-feather="trash-2"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <div class="mt-4">
            {{ $reports->links() }}
        </div>
    @else
        <div class="text-center p-6 bg-gray-100 rounded-lg">
            <i data-feather="inbox" class="w-12 h-12 mx-auto text-gray-400 mb-3"></i>
            <p class="text-gray-600">No reports found.</p>
        </div>
    @endif
</div>

<script>
    feather.replace();
</script>
@endsection
